name: Build Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix: |
        [
          { "board": "xiao_ble", "shield": "totem_left" },
          { "board": "xiao_ble", "shield": "totem_right" }
        ]
